name: Auto-deploy a prim-number-streamlit-app  
on:
  push:
    branches: [main]

jobs:
  build-and-deploy-tural:
    runs-on: ubuntu-latest
    steps:
      - name: step 1 checkout
        uses: actions/checkout@v4
      - name: step 2 setup Python so I can run streamlit
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'
      - name: step 3 install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install streamlit
          pip install rsconnect-python
      - name: step 4 create a manifest.json file
        run: |
          rsconnect write-manifest streamlit .
      - name: step 5 publish prime app
        uses: rstudio/actions/connect-publish@main
        with:
          target: connect
          CONNECT_SERVER: ${{ secrets.CONNECT_SERVER }}
          CONNECT_API_KEY: ${{ secrets.CONNECT_API_KEY }}
